export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  PROCUREMENT_MANAGER: "PROCUREMENT_MANAGER",
  WAREHOUSE_MANAGER: "WAREHOUSE_MANAGER",
  WAREHOUSE_STAFF: "WAREHOUSE_STAFF",
  SALES_MANAGER: "SALES_MANAGER",
  FINANCE_MANAGER: "FINANCE_MANAGER",
  INVENTORY_ANALYST: "INVENTORY_ANALYST",
  SUPPLIER: "SUPPLIER",
  CUSTOMER: "CUSTOMER",
};

export const INTERNAL_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN,
  ROLES.PROCUREMENT_MANAGER,
  ROLES.WAREHOUSE_MANAGER,
  ROLES.WAREHOUSE_STAFF,
  ROLES.SALES_MANAGER,
  ROLES.FINANCE_MANAGER,
  ROLES.INVENTORY_ANALYST,
];

// Roles allowed to be created via "Add Employee" dialog
export const CREATE_EMPLOYEE_ROLES = [
  ROLES.ADMIN,
  ROLES.PROCUREMENT_MANAGER,
  ROLES.WAREHOUSE_MANAGER,
  ROLES.WAREHOUSE_STAFF,
  ROLES.SALES_MANAGER,
  ROLES.FINANCE_MANAGER,
  ROLES.INVENTORY_ANALYST,
];

export const USER_MANAGEMENT_ROLES = [
    ROLES.SUPER_ADMIN,
];

export const EXTERNAL_ROLES = [ROLES.SUPPLIER, ROLES.CUSTOMER];

export const APPROVAL_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const APPROVAL_STATUS_COLORS = {
  [APPROVAL_STATUS.APPROVED]: "success",
  [APPROVAL_STATUS.PENDING]: "warning",
  [APPROVAL_STATUS.REJECTED]: "error",
};

export const ROLE_LABELS = {
  [ROLES.SUPER_ADMIN]: "Super Admin",
  [ROLES.ADMIN]: "Admin",
  [ROLES.PROCUREMENT_MANAGER]: "Procurement Manager",
  [ROLES.WAREHOUSE_MANAGER]: "Warehouse Manager",
  [ROLES.WAREHOUSE_STAFF]: "Warehouse Staff",
  [ROLES.SALES_MANAGER]: "Sales Manager",
  [ROLES.FINANCE_MANAGER]: "Finance Manager",
  [ROLES.INVENTORY_ANALYST]: "Inventory Analyst",
  [ROLES.SUPPLIER]: "Supplier",
  [ROLES.CUSTOMER]: "Customer",
};