"""add warehouse and brand description

Revision ID: 00a6a89ac994
Revises: 6d5d5431ac9a
Create Date: 2026-07-16 21:18:33.966662

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "00a6a89ac994"
down_revision: Union[str, Sequence[str], None] = "6d5d5431ac9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "brands", sa.Column("description", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "warehouses", sa.Column("description", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("warehouses", "description")
    op.drop_column("brands", "description")
    # ### end Alembic commands ###
