"""User model updated

Revision ID: 2522814506dd
Revises: eb49c2ce611d
Create Date: 2026-08-23 12:19:30.666568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2522814506dd'
down_revision: Union[str, Sequence[str], None] = 'eb49c2ce611d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=150), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('rejected_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('deactivated_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('reactivated_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('reactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'approval_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_approval_status'), 'users', ['approval_status'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['rejected_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['reactivated_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['deactivated_by'], ['id'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_approval_status'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'approval_status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'reactivated_at')
    op.drop_column('users', 'reactivated_by')
    op.drop_column('users', 'deactivated_at')
    op.drop_column('users', 'deactivated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'rejection_reason')
    op.drop_column('users', 'rejected_at')
    op.drop_column('users', 'rejected_by')
    op.drop_column('users', 'approved_at')
    op.drop_column('users', 'approved_by')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
