"""inventory enhancements and product barcode

Revision ID: 6d5d5431ac9a
Revises: 821d1691e57f
Create Date: 2026-07-07 22:48:27.905822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5d5431ac9a'
down_revision: Union[str, Sequence[str], None] = '821d1691e57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('unit_cost', sa.Float(), nullable=False))
    op.add_column('inventories', sa.Column('manufacturing_date', sa.Date(), nullable=True))
    op.add_column('inventories', sa.Column('storage_location', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('barcode', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'barcode')
    op.drop_column('inventories', 'storage_location')
    op.drop_column('inventories', 'manufacturing_date')
    op.drop_column('inventories', 'unit_cost')
    # ### end Alembic commands ###
