"""update purchase_orders and create inventory_transactions

Revision ID: a5b28e8b8357
Revises: 00a6a89ac994
Create Date: 2026-07-25 21:22:13.354229

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a5b28e8b8357"
down_revision: Union[str, Sequence[str], None] = "00a6a89ac994"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_sequences_id"), table_name="document_sequences")
    op.drop_table("document_sequences")
    op.drop_index(
        op.f("ix_inventory_transactions_id"), table_name="inventory_transactions"
    )
    op.drop_table("inventory_transactions")
    op.add_column(
        "purchase_orders",
        sa.Column("subtotal", sa.Numeric(precision=18, scale=2), nullable=False),
    )
    op.add_column(
        "purchase_orders",
        sa.Column("discount_total", sa.Numeric(precision=18, scale=2), nullable=False),
    )
    op.add_column(
        "purchase_orders",
        sa.Column("tax_total", sa.Numeric(precision=18, scale=2), nullable=False),
    )
    op.add_column(
        "purchase_orders",
        sa.Column("grand_total", sa.Numeric(precision=18, scale=2), nullable=False),
    )
    op.add_column("purchase_orders", sa.Column("remarks", sa.Text(), nullable=True))
    op.add_column(
        "purchase_orders",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.alter_column(
        "purchase_orders",
        "po_number",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "purchase_orders",
        "status",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    op.create_index(
        "idx_po_created_at", "purchase_orders", ["created_at"], unique=False
    )
    op.create_index("idx_po_status", "purchase_orders", ["status"], unique=False)
    op.create_index("idx_po_supplier", "purchase_orders", ["supplier_id"], unique=False)
    op.create_index(
        "idx_po_warehouse", "purchase_orders", ["warehouse_id"], unique=False
    )
    op.drop_constraint(
        op.f("purchase_orders_received_by_fkey"), "purchase_orders", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("purchase_orders_product_id_fkey"), "purchase_orders", type_="foreignkey"
    )
    op.drop_column("purchase_orders", "received_by")
    op.drop_column("purchase_orders", "actual_delivery_date")
    op.drop_column("purchase_orders", "quantity")
    op.drop_column("purchase_orders", "product_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "purchase_orders",
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "purchase_orders",
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "purchase_orders",
        sa.Column(
            "actual_delivery_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "purchase_orders",
        sa.Column("received_by", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("purchase_orders_product_id_fkey"),
        "purchase_orders",
        "products",
        ["product_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("purchase_orders_received_by_fkey"),
        "purchase_orders",
        "users",
        ["received_by"],
        ["id"],
    )
    op.drop_index("idx_po_warehouse", table_name="purchase_orders")
    op.drop_index("idx_po_supplier", table_name="purchase_orders")
    op.drop_index("idx_po_status", table_name="purchase_orders")
    op.drop_index("idx_po_created_at", table_name="purchase_orders")
    op.alter_column(
        "purchase_orders",
        "status",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "purchase_orders",
        "po_number",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("purchase_orders", "updated_at")
    op.drop_column("purchase_orders", "remarks")
    op.drop_column("purchase_orders", "grand_total")
    op.drop_column("purchase_orders", "tax_total")
    op.drop_column("purchase_orders", "discount_total")
    op.drop_column("purchase_orders", "subtotal")
    op.create_table(
        "inventory_transactions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("inventory_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "transaction_type",
            postgresql.ENUM(
                "CREATE",
                "INCREASE",
                "DECREASE",
                "RESERVE",
                "RELEASE",
                "ADJUSTMENT",
                name="inventorytransactiontype",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("quantity_before", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("quantity_delta", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("quantity_after", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "reserved_quantity_before",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "reserved_quantity_after", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "available_quantity_before",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "available_quantity_after",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("reason", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "reference_type",
            postgresql.ENUM(
                "INVENTORY",
                "PURCHASE_ORDER",
                "GOODS_RECEIPT",
                "SALES_ORDER",
                "STOCK_TRANSFER",
                "RETURN",
                "ADJUSTMENT",
                name="inventoryreferencetype",
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("reference_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["inventory_id"],
            ["inventories.id"],
            name=op.f("inventory_transactions_inventory_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("inventory_transactions_pkey")),
    )
    op.create_index(
        op.f("ix_inventory_transactions_id"),
        "inventory_transactions",
        ["id"],
        unique=False,
    )
    op.create_table(
        "document_sequences",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "document_type",
            postgresql.ENUM(
                "PURCHASE_ORDER",
                "SALES_ORDER",
                "GOODS_RECEIPT",
                "STOCK_TRANSFER",
                "STOCK_ADJUSTMENT",
                "PURCHASE_RETURN",
                "SALES_RETURN",
                "INVENTORY_COUNT",
                name="documenttype",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("sequence_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("last_sequence", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("document_sequences_pkey")),
        sa.UniqueConstraint(
            "document_type",
            "sequence_date",
            name=op.f("uq_document_sequence_type_date"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_document_sequences_id"), "document_sequences", ["id"], unique=False
    )
    # ### end Alembic commands ###
