"""Customer module upgraded and Supplier module modified

Revision ID: b115b34b0338
Revises: 2522814506dd
Create Date: 2026-08-23 13:11:12.815809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b115b34b0338'
down_revision: Union[str, Sequence[str], None] = '2522814506dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('reactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('customers', 'contact_person',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=True)
    op.alter_column('customers', 'address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('customers', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customers', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customers', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('customers_user_id_key'), 'customers', type_='unique')
    op.create_index(op.f('ix_customers_is_active'), 'customers', ['is_active'], unique=False)
    op.create_index(op.f('ix_customers_is_verified'), 'customers', ['is_verified'], unique=False)
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=True)
    op.create_unique_constraint(None, 'customers', ['gst_number'])
    op.drop_column('customers', 'pincode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('pincode', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_verified'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_active'), table_name='customers')
    op.create_unique_constraint(op.f('customers_user_id_key'), 'customers', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('customers', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('customers', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('customers', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('customers', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('customers', 'phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('customers', 'contact_person',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('customers', 'reactivated_at')
    op.drop_column('customers', 'deactivated_at')
    op.drop_column('customers', 'postal_code')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###
