"""Supplier module modified

Revision ID: b12aaea741e7
Revises: b115b34b0338
Create Date: 2026-08-23 21:40:31.481316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b12aaea741e7'
down_revision: Union[str, Sequence[str], None] = 'b115b34b0338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods_receipts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('goods_receipts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('suppliers', 'gst_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('suppliers', 'address',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('suppliers', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('suppliers', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('suppliers', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('suppliers', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('suppliers', 'supplier_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('suppliers', 'lead_time_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('suppliers', 'payment_terms',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'payment_terms',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('suppliers', 'lead_time_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('suppliers', 'supplier_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('suppliers', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('suppliers', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('suppliers', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('suppliers', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('suppliers', 'address',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('suppliers', 'gst_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('goods_receipts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('goods_receipts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
