"""update sales_orders

Revision ID: cbede1cedb76
Revises: a5b28e8b8357
Create Date: 2026-08-16 23:09:28.963880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbede1cedb76'
down_revision: Union[str, Sequence[str], None] = 'a5b28e8b8357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_sequences_id'), table_name='document_sequences')
    op.drop_table('document_sequences')
    op.drop_index(op.f('idx_goods_receipt_line_goods_receipt'), table_name='goods_receipt_lines')
    op.drop_index(op.f('idx_goods_receipt_line_product'), table_name='goods_receipt_lines')
    op.drop_index(op.f('idx_goods_receipt_line_purchase_order_line'), table_name='goods_receipt_lines')
    op.drop_table('goods_receipt_lines')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('idx_goods_receipt_created_at'), table_name='goods_receipts')
    op.drop_index(op.f('idx_goods_receipt_grn_number'), table_name='goods_receipts')
    op.drop_index(op.f('idx_goods_receipt_purchase_order'), table_name='goods_receipts')
    op.drop_index(op.f('idx_goods_receipt_status'), table_name='goods_receipts')
    op.drop_index(op.f('idx_goods_receipt_warehouse'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.add_column('sales_order_lines', sa.Column('inventory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales_order_lines', 'inventories', ['inventory_id'], ['id'])
    op.add_column('sales_orders', sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('sales_orders', sa.Column('discount_total', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('sales_orders', sa.Column('tax_total', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('sales_orders', sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('sales_orders', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('sales_orders', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('sales_orders', 'so_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('sales_orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_sales_orders_id'), table_name='sales_orders')
    op.drop_constraint(op.f('sales_orders_so_number_key'), 'sales_orders', type_='unique')
    op.create_index('idx_sales_order_created_at', 'sales_orders', ['created_at'], unique=False)
    op.create_index('idx_sales_order_customer', 'sales_orders', ['customer_id'], unique=False)
    op.create_index('idx_sales_order_status', 'sales_orders', ['status'], unique=False)
    op.create_index('idx_sales_order_warehouse', 'sales_orders', ['warehouse_id'], unique=False)
    op.create_unique_constraint('uq_sales_order_so_number', 'sales_orders', ['so_number'])
    op.drop_constraint(op.f('sales_orders_product_id_fkey'), 'sales_orders', type_='foreignkey')
    op.drop_column('sales_orders', 'total_price')
    op.drop_column('sales_orders', 'sold_at')
    op.drop_column('sales_orders', 'product_id')
    op.drop_column('sales_orders', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_orders', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sales_orders', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sales_orders', sa.Column('sold_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('sales_orders', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('sales_orders_product_id_fkey'), 'sales_orders', 'products', ['product_id'], ['id'])
    op.drop_constraint('uq_sales_order_so_number', 'sales_orders', type_='unique')
    op.drop_index('idx_sales_order_warehouse', table_name='sales_orders')
    op.drop_index('idx_sales_order_status', table_name='sales_orders')
    op.drop_index('idx_sales_order_customer', table_name='sales_orders')
    op.drop_index('idx_sales_order_created_at', table_name='sales_orders')
    op.create_unique_constraint(op.f('sales_orders_so_number_key'), 'sales_orders', ['so_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_sales_orders_id'), 'sales_orders', ['id'], unique=False)
    op.alter_column('sales_orders', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('sales_orders', 'so_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('sales_orders', 'created_at')
    op.drop_column('sales_orders', 'remarks')
    op.drop_column('sales_orders', 'grand_total')
    op.drop_column('sales_orders', 'tax_total')
    op.drop_column('sales_orders', 'discount_total')
    op.drop_column('sales_orders', 'subtotal')
    op.drop_constraint(None, 'sales_order_lines', type_='foreignkey')
    op.drop_column('sales_order_lines', 'inventory_id')
    op.create_table('goods_receipts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grn_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('purchase_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'CANCELLED', name='goodsreceiptstatus'), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('received_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cancelled_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('goods_receipts_approved_by_fkey')),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], name=op.f('goods_receipts_cancelled_by_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('goods_receipts_created_by_fkey')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('goods_receipts_purchase_order_id_fkey')),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], name=op.f('goods_receipts_received_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('goods_receipts_updated_by_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('goods_receipts_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('goods_receipts_pkey')),
    sa.UniqueConstraint('grn_number', name=op.f('uq_goods_receipt_grn_number'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_goods_receipt_warehouse'), 'goods_receipts', ['warehouse_id'], unique=False)
    op.create_index(op.f('idx_goods_receipt_status'), 'goods_receipts', ['status'], unique=False)
    op.create_index(op.f('idx_goods_receipt_purchase_order'), 'goods_receipts', ['purchase_order_id'], unique=False)
    op.create_index(op.f('idx_goods_receipt_grn_number'), 'goods_receipts', ['grn_number'], unique=False)
    op.create_index(op.f('idx_goods_receipt_created_at'), 'goods_receipts', ['created_at'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_type', postgresql.ENUM('CREATE', 'INCREASE', 'DECREASE', 'RESERVE', 'RELEASE', 'ADJUSTMENT', name='inventorytransactiontype'), autoincrement=False, nullable=False),
    sa.Column('quantity_before', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_delta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_after', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reserved_quantity_before', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reserved_quantity_after', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available_quantity_before', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available_quantity_after', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_type', postgresql.ENUM('INVENTORY', 'PURCHASE_ORDER', 'GOODS_RECEIPT', 'SALES_ORDER', 'STOCK_TRANSFER', 'RETURN', 'ADJUSTMENT', name='inventoryreferencetype'), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], name=op.f('inventory_transactions_inventory_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_transactions_pkey'))
    )
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_table('goods_receipt_lines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('goods_receipt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('line_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchase_order_line_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_name_snapshot', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('product_sku_snapshot', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('batch_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('accepted_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rejected_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], name=op.f('goods_receipt_lines_goods_receipt_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('goods_receipt_lines_product_id_fkey')),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], name=op.f('goods_receipt_lines_purchase_order_line_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('goods_receipt_lines_pkey')),
    sa.UniqueConstraint('goods_receipt_id', 'line_number', name=op.f('uq_goods_receipt_line_number'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_goods_receipt_line_purchase_order_line'), 'goods_receipt_lines', ['purchase_order_line_id'], unique=False)
    op.create_index(op.f('idx_goods_receipt_line_product'), 'goods_receipt_lines', ['product_id'], unique=False)
    op.create_index(op.f('idx_goods_receipt_line_goods_receipt'), 'goods_receipt_lines', ['goods_receipt_id'], unique=False)
    op.create_table('document_sequences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_type', postgresql.ENUM('PURCHASE_ORDER', 'SALES_ORDER', 'GOODS_RECEIPT', 'STOCK_TRANSFER', 'STOCK_ADJUSTMENT', 'PURCHASE_RETURN', 'SALES_RETURN', 'INVENTORY_COUNT', name='documenttype'), autoincrement=False, nullable=False),
    sa.Column('sequence_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('last_sequence', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('document_sequences_pkey')),
    sa.UniqueConstraint('document_type', 'sequence_date', name=op.f('uq_document_sequence_type_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_document_sequences_id'), 'document_sequences', ['id'], unique=False)
    # ### end Alembic commands ###
