"""update Stock transfers

Revision ID: eb49c2ce611d
Revises: cbede1cedb76
Create Date: 2026-08-17 22:59:25.979220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb49c2ce611d'
down_revision: Union[str, Sequence[str], None] = 'cbede1cedb76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_transfers', sa.Column('transfer_number', sa.String(length=50), nullable=False))
    op.add_column('stock_transfers', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('stock_transfers', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('stock_transfers', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('stock_transfers', 'initiated_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_stock_transfers_id'), table_name='stock_transfers')
    op.create_index('idx_stock_transfer_created_at', 'stock_transfers', ['created_at'], unique=False)
    op.create_index('idx_stock_transfer_destination_warehouse', 'stock_transfers', ['destination_warehouse_id'], unique=False)
    op.create_index('idx_stock_transfer_number', 'stock_transfers', ['transfer_number'], unique=False)
    op.create_index('idx_stock_transfer_source_warehouse', 'stock_transfers', ['source_warehouse_id'], unique=False)
    op.create_index('idx_stock_transfer_status', 'stock_transfers', ['status'], unique=False)
    op.create_unique_constraint('uq_stock_transfer_number', 'stock_transfers', ['transfer_number'])
    op.drop_constraint(op.f('stock_transfers_product_id_fkey'), 'stock_transfers', type_='foreignkey')
    op.drop_column('stock_transfers', 'product_id')
    op.drop_column('stock_transfers', 'quantity')
    op.drop_column('stock_transfers', 'transferred_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_transfers', sa.Column('transferred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('stock_transfers', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stock_transfers', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('stock_transfers_product_id_fkey'), 'stock_transfers', 'products', ['product_id'], ['id'])
    op.drop_constraint('uq_stock_transfer_number', 'stock_transfers', type_='unique')
    op.drop_index('idx_stock_transfer_status', table_name='stock_transfers')
    op.drop_index('idx_stock_transfer_source_warehouse', table_name='stock_transfers')
    op.drop_index('idx_stock_transfer_number', table_name='stock_transfers')
    op.drop_index('idx_stock_transfer_destination_warehouse', table_name='stock_transfers')
    op.drop_index('idx_stock_transfer_created_at', table_name='stock_transfers')
    op.create_index(op.f('ix_stock_transfers_id'), 'stock_transfers', ['id'], unique=False)
    op.alter_column('stock_transfers', 'initiated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stock_transfers', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('stock_transfers', 'created_at')
    op.drop_column('stock_transfers', 'remarks')
    op.drop_column('stock_transfers', 'transfer_number')
    # ### end Alembic commands ###
