from enum import Enum


class UserRole(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "ADMIN"
    PROCUREMENT_MANAGER = "PROCUREMENT_MANAGER"
    WAREHOUSE_MANAGER = "WAREHOUSE_MANAGER"
    WAREHOUSE_STAFF = "WAREHOUSE_STAFF"
    SALES_MANAGER = "SALES_MANAGER"
    FINANCE_MANAGER = "FINANCE_MANAGER"
    INVENTORY_ANALYST = "INVENTORY_ANALYST"
    SUPPLIER = "SUPPLIER"
    CUSTOMER = "CUSTOMER"


class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
